package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from d:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u5/2488/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, March 18, 2014 1:10:02 AM PDT
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
   * The CDR Encapsulation encoding.
   * @see CodecFactory
   */
  public static final short value = (short)(0);
}
